# Numpy

Why Use NumPy Instead of Lists, Tuples, Sets, or Dicts?

1:-Performance: NumPy arrays are significantly faster than Python lists due to their fixed datatype 
                and optimized C backend(NumPy's core operations are implemented in C,).
            
2:-Memory Efficiency: NumPy uses contiguous memory allocation, which makes it more space-efficient than lists.   
3:-Vectorized Operations: Unlike lists, NumPy allows operations to be applied directly to the entire array, 
        avoiding Python loops.
        
4:-Advanced Mathematical Functions: NumPy supports linear algebra, statistics, and more, which are not available in built-in       data structures.

You can apply loops in NumPy, but it's generally not recommended because loops in Python are slow. 

Instead, NumPy provides vectorized operations, which are much faster since they use the optimized C backend.

NumPy vectorized operations is ~40x faster than python loop

# NumPy is best for machine learning, scientific computing.

In [5]:
import numpy as np

list1=[1,2,3,3,3,3,444,555,66]
list1
#here we have a list and we have converted into array, so we need to use numpy libarary for this
list1_array=np.array(list1)
list1_array

array([  1,   2,   3,   3,   3,   3, 444, 555,  66])

In [8]:
#A retail company wants to forecast future demand based on past sales data.
#just assume this is 12 months data Jan to Dec

import numpy as np

sales_data=np.array([100,105,107,98,99,102,103,108,109,110,112,114])
sales_data

future_demand=sales_data*1.1 #here we are assuming 10 percent of grth
future_demand

array([110. , 115.5, 117.7, 107.8, 108.9, 112.2, 113.3, 118.8, 119.9,
       121. , 123.2, 125.4])

In [13]:
#A factory produces 10,000 items daily, and they need to calculate the defect percentage.

import numpy as np
total_items= [10000,9000,8000,4000,9700]
total_items=np.array(total_items)
total_items

defect_products=[120,200,80,35,91]
defect_products=np.array(defect_products)
defect_products

defect_percentage=(defect_products/total_items)*100
defect_percentage

array([1.2       , 2.22222222, 1.        , 0.875     , 0.93814433])

In [25]:
#A hospital needs to process MRI scans stored as pixel intensity arrays.

import numpy as np

image=np.random.randint(0,256)
image

#here numpy is libraray
# random is module
#randint is a function

#currently image is giving random number between 0 to 256

#for example if we want to create a 3 rows and 3 columns then we need to provide like this
image1=np.random.randint(0,256,(3,3))
image1

#for example if we want to create a 4 rows and 4 columns then we need to provide like this
image1=np.random.randint(0,256,(4,4))
image1

#for example if we want to create a 5 rows and 6 columns then we need to provide like this
image2=np.random.randint(0,256,(5,6))
image2


image_final=np.random.randint(0,256,(512,512)) #for grey image
image_final = image_final / 255 
image_final
print(image_final)




[[0.5254902  0.89019608 0.58823529 ... 0.85882353 0.10980392 0.7372549 ]
 [0.7372549  0.99215686 0.90980392 ... 0.18431373 0.95686275 0.8627451 ]
 [0.64313725 0.99607843 0.37647059 ... 0.77254902 0.72156863 0.22745098]
 ...
 [0.90588235 0.36470588 0.44313725 ... 0.52156863 0.28627451 0.44705882]
 [0.4        0.78039216 0.29803922 ... 0.80784314 0.7254902  0.84705882]
 [0.7254902  0.89803922 0.24705882 ... 0.85882353 0.70588235 0.70980392]]


In [28]:
#A solar panel company needs to analyze sunlight intensity data to optimize energy production.

solar_data = np.array([3.4, 4.2, 3.9, 4.5, 4.7])
solar_data =np.mean(solar_data)
solar_data

4.14