In [1]:
#update via slicing

import numpy as np

ab1=np.arange(20)
ab1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
ab2= ab1[4:5]=444444
ab2

444444

In [5]:
ab1[4:5]=99999
ab1

array([    0,     1,     2,     3, 99999,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19])

In [14]:
#you need to reverse half array as reverse order and half remain same

ab2=np.arange(10)
ab2
ab3=ab2[5:]
ab3

array([5, 6, 7, 8, 9])

In [23]:
ab2=np.arange(10)
ab2
ab4=ab2[5:][::-1]
ab4

ab4=np.concatenate((ab2[:5] , ab2[5:][::-1]))
ab4

array([0, 1, 2, 3, 4, 9, 8, 7, 6, 5])

In [21]:
import numpy as np

ab2 = np.arange(10)  # Creates an array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Reverse the second half while keeping the first half unchanged
ab3 = np.concatenate((ab2[:5], ab2[5:][::-1]))

print(ab3)

[0 1 2 3 4 9 8 7 6 5]


In [27]:
# Do you know in Numpy also we have view similar to sql, How to check that

ab4=np.arange(10)
ab4

ab5=ab4[:5]
ab5

array([0, 1, 2, 3, 4])

In [28]:
#here you can check both shrae the same memorory
np.shares_memory(ab4,ab5)

True

In [30]:
#if we update one second automtically updated, here you can see that we have udated only ab5 
#but in backend its updated the ab4 as well because of sharememory or they will store at same moenory

ab5[0:1]=200
ab5
print(ab4)
print(ab5)

[200   1   2   3   4   5   6   7   8   9]
[200   1   2   3   4]


In [31]:
#Even if id() values are different, they can still share memory at the NumPy level.
print(id(ab4))
print(id(ab5))

2460599487920
2460599695664


In [38]:
#if we want to force a copy , if we will use copy function then we can easly do this
#means it will not effect the base things

ab6=np.arange(10)
ab6

ab7=ab6[:2].copy()
ab7

ab7[1:2]=999999
print(ab7)
print(ab6)
np.shares_memory(ab6,ab7)

[     0 999999]
[0 1 2 3 4 5 6 7 8 9]


False

#for example we need only numbers which are divide by 2 from an array


In [43]:
#randint function to generate total numbers range from (start_range,end_range, number of elements)

#gives only number which are divide by 2

ab8=np.random.randint(1,20,10)
ab8
mask=(ab8%2==0)
new_dataset=ab8[mask]
new_dataset

array([16,  6, 14,  4,  6])

In [46]:
#randint function to generate total numbers range from (start_range,end_range, number of elements)

#gives only number which are divide by 5

ab8=np.random.randint(1,100,10)
ab8
mask1=(ab8%5==0)
new_dataset=ab8[mask1]
new_dataset

array([30, 35, 70])

In [52]:
#for example now we have requirement where we want to implement all even number will becoame -1

ab8=np.random.randint(1,100,10)
ab8



array([48, 69, 50,  4, 98, 71, 15,  4, 21, 20])

In [63]:
ab8[ab8 % 2== 0 ] = -1
ab8

array([97, -1, -1, 41, 49, -1, -1, 97, -1, -1])

In [61]:
import numpy as np

# Generate an array of 10 random integers between 1 and 100
ab8 = np.random.randint(1, 100, 10)
print("Original array:", ab8)

# Replace all even numbers with -1
ab8[ab8 % 2 == 0] = -1
print("Modified array:", ab8)

Original array: [97  6 54 41 49 68 46 97 12 64]
Modified array: [97 -1 -1 41 49 -1 -1 97 -1 -1]


In [71]:
#for example if if have array and we need one or two elements mutiple times
#
ab9=np.arange(30)
ab9
ab9[[1,29,1,29,1,3]]

array([ 1, 29,  1, 29,  1,  3])

In [73]:
ab10=np.random.randint(1,20,10)
ab10
ab10[[1,2,1,2,1,2]]

array([11,  7, 11,  7, 11,  7])