# reading data from sample superstore

np.loadtxt
When working with small-to-medium-sized structured text files.
When all data in the file is numerical.
When you want fast and efficient loading into NumPy arrays.



In [8]:
import numpy as np

In [16]:
data1=np.loadtxt("A:\LLM\Sample_superstore.txt", delimiter=",", dtype=float)
data1

#load txt enable to read string columns
#even it is not taking header as a string values

ValueError: could not convert string to float: '261.96\t2\t0\t41.9136'

In [22]:
#here in loadtxt we need to provide only numerical vlaues, we can skip header as well
#we have option for skip header
#similarly we can pass parameter max_rows also
#if values are coming another scienticfic then we can supress then via set_printoptions

data2=np.loadtxt("A:\LLM\Sample_superstore.txt" , max_rows=30)
np.set_printoptions(suppress=True) 
data2

array([[  261.96  ,     2.    ,     0.    ,    41.9136],
       [  731.94  ,     3.    ,     0.    ,   219.582 ],
       [   14.62  ,     2.    ,     0.    ,     6.8714],
       [  957.5775,     5.    ,     0.45  ,  -383.031 ],
       [   22.368 ,     2.    ,     0.2   ,     2.5164],
       [   48.86  ,     7.    ,     0.    ,    14.1694],
       [    7.28  ,     4.    ,     0.    ,     1.9656],
       [  907.152 ,     6.    ,     0.2   ,    90.7152],
       [   18.504 ,     3.    ,     0.2   ,     5.7825],
       [  114.9   ,     5.    ,     0.    ,    34.47  ],
       [ 1706.184 ,     9.    ,     0.2   ,    85.3092],
       [  911.424 ,     4.    ,     0.2   ,    68.3568],
       [   15.552 ,     3.    ,     0.2   ,     5.4432],
       [  407.976 ,     3.    ,     0.2   ,   132.5922],
       [   68.81  ,     5.    ,     0.8   ,  -123.858 ],
       [    2.544 ,     3.    ,     0.8   ,    -3.816 ],
       [  665.88  ,     6.    ,     0.    ,    13.3176],
       [   55.5   ,     2.    ,

In [24]:
#now this is a set of array and you are using slicing and indexing to access the data
#for example I have used slicing then it will remove the rows
data2[1:3]

array([[731.94  ,   3.    ,   0.    , 219.582 ],
       [ 14.62  ,   2.    ,   0.    ,   6.8714]])

In [25]:
data2[1:3][1:2]

array([[14.62  ,  2.    ,  0.    ,  6.8714]])

In [28]:
#here i have used indexing
#first row and third column values

data2[1,3]

219.582

In [30]:
data2[3][2]

0.45

In [33]:
#if we need particular column then we can use this.

data2[:,2]

array([0.  , 0.  , 0.  , 0.45, 0.2 , 0.  , 0.  , 0.2 , 0.2 , 0.  , 0.2 ,
       0.2 , 0.2 , 0.2 , 0.8 , 0.8 , 0.  , 0.  , 0.  , 0.2 , 0.2 , 0.  ,
       0.  , 0.3 , 0.  , 0.2 , 0.  , 0.5 , 0.7 , 0.2 ])

In [35]:
#How to perform transpose in python(numpy)
#oNLY WE NEED TO use T
#IT will tranpose the data row into columns and columns into rows

data3=data2.T
data3

array([[  261.96  ,   731.94  ,    14.62  ,   957.5775,    22.368 ,
           48.86  ,     7.28  ,   907.152 ,    18.504 ,   114.9   ,
         1706.184 ,   911.424 ,    15.552 ,   407.976 ,    68.81  ,
            2.544 ,   665.88  ,    55.5   ,     8.56  ,   213.48  ,
           22.72  ,    19.46  ,    60.34  ,    71.372 ,  1044.63  ,
           11.648 ,    90.57  ,  3083.43  ,     9.618 ,   124.2   ],
       [    2.    ,     3.    ,     2.    ,     5.    ,     2.    ,
            7.    ,     4.    ,     6.    ,     3.    ,     5.    ,
            9.    ,     4.    ,     3.    ,     3.    ,     5.    ,
            3.    ,     6.    ,     2.    ,     2.    ,     3.    ,
            4.    ,     7.    ,     7.    ,     2.    ,     3.    ,
            2.    ,     3.    ,     7.    ,     2.    ,     3.    ],
       [    0.    ,     0.    ,     0.    ,     0.45  ,     0.2   ,
            0.    ,     0.    ,     0.2   ,     0.2   ,     0.    ,
            0.2   ,     0.2   ,     0.2   ,   

In [36]:
data4=data3.T
data4

array([[  261.96  ,     2.    ,     0.    ,    41.9136],
       [  731.94  ,     3.    ,     0.    ,   219.582 ],
       [   14.62  ,     2.    ,     0.    ,     6.8714],
       [  957.5775,     5.    ,     0.45  ,  -383.031 ],
       [   22.368 ,     2.    ,     0.2   ,     2.5164],
       [   48.86  ,     7.    ,     0.    ,    14.1694],
       [    7.28  ,     4.    ,     0.    ,     1.9656],
       [  907.152 ,     6.    ,     0.2   ,    90.7152],
       [   18.504 ,     3.    ,     0.2   ,     5.7825],
       [  114.9   ,     5.    ,     0.    ,    34.47  ],
       [ 1706.184 ,     9.    ,     0.2   ,    85.3092],
       [  911.424 ,     4.    ,     0.2   ,    68.3568],
       [   15.552 ,     3.    ,     0.2   ,     5.4432],
       [  407.976 ,     3.    ,     0.2   ,   132.5922],
       [   68.81  ,     5.    ,     0.8   ,  -123.858 ],
       [    2.544 ,     3.    ,     0.8   ,    -3.816 ],
       [  665.88  ,     6.    ,     0.    ,    13.3176],
       [   55.5   ,     2.    ,

In [37]:
#numpy is similar to proc means in SAS
#for example we want to calculate the standard deviation of this
#its very easy here, Only we need to mention we want to claucltae the rows wise or column wise
#that also decided by axis value

#when we mention axis=0 then it means compute by columns not rows

data5=data4.std(axis=0)
data5

array([654.51874991,   1.94050394,   0.2345504 , 318.32923069])

In [38]:
# we want to do calucation by row wise the we need to used axis =1

data6=data4.std(axis=1)
data6

array([ 108.39064382,  298.40549434,    5.63469319,  494.87211302,
          9.04583484,   18.78192136,    2.69260578,  380.5102834 ,
          6.99997146,   45.98278666,  725.91296678,  385.13888605,
          5.79183055,  165.91653342,   69.81210298,    2.69611276,
        285.58518655,   22.61263516,    3.19804082,   89.86493636,
          8.55234985,    7.15751102,   23.5192086 ,   30.7388157 ,
        428.46229143,    4.35630941,   37.33701073, 1715.49604841,
          5.91214903,   51.40237523])

In [39]:
data7=np.argmax(data4, axis=1)
data7

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [ ]:
#In Numpy we have concept called broadcasting