In [1]:
import numpy as np

In [2]:
#how to generate random number
np.random.rand(5)

array([0.40893025, 0.57281619, 0.57881784, 0.24579898, 0.00878451])

In [5]:
#rand normal function

ab=np.random.randn(5)
ab

array([-0.51545576, -0.02941869,  2.81320126,  1.0452847 ,  1.04180638])

In [7]:
type(ab)

numpy.ndarray

In [8]:
ab.dtype

dtype('float64')

In [11]:
#a range function for setting the range

ab1=np.arange(5)
ab1

array([0, 1, 2, 3, 4])

In [12]:
#here dtype is a type of format
ab2=np.arange(5, dtype='float')
ab2

array([0., 1., 2., 3., 4.])

In [15]:
#if you want to pass string values in a array function, please make sure to pass values in list 

ab2=np.array(['ram',"jai","shree"])
ab2

array(['ram', 'jai', 'shree'], dtype='<U5')

In [16]:
type(ab2)

numpy.ndarray

In [18]:
ab2.dtype

dtype('<U5')

In [19]:
#how to pass boolean values , same we need to pass in list, reason is simple array is a function 
#and it will take only one argument , so we want to pass mutiple values then 

ab3=np.array([True,False])
ab3

array([ True, False])

In [20]:
type(ab3)

numpy.ndarray

In [22]:
ab3.dtype

dtype('bool')

# how to access elements in python

Two ways via slicing and Via indexing

In [23]:
ab4=np.arange(10)
ab4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#suppose you want to access the 8 element from this array

In [25]:
#to access 8 element we need to mention 7 beacuse n-1 logic(start with zero)
ab4[7]

7

In [28]:
#suppose we have diagonal matrix

ab5=np.diag([1,2,3,4])
ab5

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [35]:
#now we want to access the elements of this matrix then we use list here, so make sure ab5 is not a function 
#so we are not passing any bracket () only square bracket
ab5[2,2]

3

In [36]:
#if you want to update any value then also it is possible

ab5[1,1]=55
ab5

array([[ 1,  0,  0,  0],
       [ 0, 55,  0,  0],
       [ 0,  0,  3,  0],
       [ 0,  0,  0,  4]])

In [37]:
ab5[1,3]=551
ab5

array([[  1,   0,   0,   0],
       [  0,  55,   0, 551],
       [  0,   0,   3,   0],
       [  0,   0,   0,   4]])

In [38]:
#Means if you are form sql background then how you slecet particular columns like this
#select col1, col2 from table1
#here in python we can access via indexing and slicing 
#via indexing

ab5[3,1]

0

In [39]:
#similary if you are using update statment in sql like update table1 set col1=5 where col1=abc
#here update also we can do via indexing and slicing (only use the assignemnet opeartor)

ab5[3,0]=9876
ab5


array([[   1,    0,    0,    0],
       [   0,   55,    0,  551],
       [   0,    0,    3,    0],
       [9876,    0,    0,    4]])

In [40]:
#for example if you want to you want to access from a matrix

ab6=np.arange(20)
ab6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
#now you want to acees particular columns for exzmple col5,col6 (select col5,col6 from table1)

#via slicing

ab6[5:6]

array([5])

In [48]:
#we can use step thing also in indeixng

ab7=ab6[5:10:2]
ab7

array([5, 7, 9])