In [2]:
#super efficent libraray
import numpy as np

#here we have learn lot of basic things
how to create an array from list
how to check array is 1d or 2d or nd (using ndim)
how many rows and columns are here (shape)
use of arange function(to genearte range )
arange function have 3 arguments (start, end, step)
linspace function have 3 argument(start,end, linear_space)
diag function to create diagnal values
ones function to create all ones matrix(but make sure they will take only one argument ,if you want to craete a matrix then pass tuple)
zero function to create all zero (but make sure they will take only one argument ,if you want to craete a matrix then pass tuple)
rand function to generate random number , please make sure to use random module in numpy.

In [5]:
#how to create array
#it will take list as input
#please make sure to use array function here

list1=[10,20,30,40,50,60]

list2=np.array(list1)
list2

array([10, 20, 30, 40, 50, 60])

In [7]:
#how to check array dimension
#use ndim function

list2.ndim

1

In [8]:
#how to create a two dimension array
#then we need two lists 
#only list of rwo
#another list for column

l1=[1,2,3,4]
l2=[5,6,7,8]

two_dim=np.array(l1,l2)
two_dim

#this will throw an error beacuse in array we can pass only one element

TypeError: Field elements must be 2- or 3-tuples, got '5'

In [9]:
#how to create a two dimension array
#then we need two lists 
#only list of rwo
#another list for column
#to avoid that error we can  pass mutiple list we need to pass list here

l1=[1,2,3,4]
l2=[5,6,7,8]

two_dim=np.array([l1,l2])
two_dim



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
two_dim.ndim

2

In [12]:
#if you want to know how many rows and how many columns then use shape

two_dim.shape

(2, 4)

In [23]:
l1=[1,2,4,5]
l2=[5,6,6,7]
l3=[44,55,66,77]

#to create mutiple dimesion list we need to create list inside list-->list inside list
#like here you can see lot of brackets

four_dim=np.array([[[l1,l2]], [[l3,l2]]])
four_dim

array([[[[ 1,  2,  4,  5],
         [ 5,  6,  6,  7]]],


       [[[44, 55, 66, 77],
         [ 5,  6,  6,  7]]]])

In [24]:
four_dim.ndim

4

In [25]:
four_dim.shape

(2, 1, 2, 4)

In [ ]:
# Do you know 1d array is called vector
#Do you know 2d array is called matrix
#do you know nd arry is called as tensor

In [27]:
#till now we have learn create numpy array with help of list
#let's create numpy array with help of arange function

a1=np.arange(1,10)
a1

#here 1 is starting value and 10 is ending value

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a1=np.arange(1,10,2)
a1

#here 1 is starting value and 10 is ending value
#3rd argument in arange function "step"

array([1, 3, 5, 7, 9])

In [33]:
#linear space function
#start and end
#third point breaking into linear space
a2=np.linspace(1,2)
a2



array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [36]:
a3=np.linspace(1,10,2)
a3
#for example here we mention linear space into 2 then it will divide our range into two euql parts
#like in output 1 and 10

array([ 1., 10.])

In [37]:
a3=np.linspace(1,10,5)
a3
#for example here we mention linear space into 5 then it will divide our range into 5 euql parts
#like in output 1 and 10  1.  ,  3.25,  5.5 ,  7.75, 10. 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
#things we learn
#numpy is import libraray for all calculation
#how to create an array from list , use numpy.array()
#how to create 2 dim array, use numpy.array([l1,l2]) two list
#how to check that array is one dim or two dim then use ndim
#how to check row and columns then use shape

In [39]:
#function ones to create ones
a4=np.ones(3)
a4

array([1., 1., 1.])

In [42]:
#function ones to create ones
#here make sure ones take only one value in argument, but if we want to take more values then we need to pass tuple
a5=np.ones((3,3))
a5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
#we have zeros function as well
a6=np.zeros(3)
a6

array([0., 0., 0.])

In [46]:
#we have zeros function as well, here also we need to pass an tuple
a7=np.zeros((3,3))
a7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
#how to create any emplty array

a8=[]
a9=np.array(a8)
a9

array([], dtype=float64)

In [49]:
#how to create an identiy matrix
#identiy matrix means diagnal elements are one
#so we have eye function (eye means identical i)

a9=np.eye(3,3)
a9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
a10=np.eye(10,10)
a10

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [54]:
#similarly we have diagnoal function, 
#here we are passing list and it will put all the values in diagnal

a11=np.diag([1,3,5,6,7])
a11

array([[1, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 7]])

In [55]:
#using diag function and using list as constant
l33=[1,2,3,3,455]

a12=np.diag(l33)
a12

array([[  1,   0,   0,   0,   0],
       [  0,   2,   0,   0,   0],
       [  0,   0,   3,   0,   0],
       [  0,   0,   0,   3,   0],
       [  0,   0,   0,   0, 455]])

In [56]:
#now for example we want to fetch only diagnal values form matrix
#same diag function is helpful here, but we need to make sure pass the matrix

a13=np.diag(a12)
a13

array([  1,   2,   3,   3, 455])

In [57]:
#rand function to generate the random number
#please makesure we need to call random module for this
#in Numpy library we have random package and in random package we have rand function

a14=np.random.rand(5)
a14

array([0.18614946, 0.63827279, 0.40352334, 0.22330108, 0.69083568])

In [58]:
a15=np.random.rand(5,4)
a15

#here we have generated random matrix
# 5,4
# 5 rows and 4 columns

array([[0.61791565, 0.81402219, 0.41117206, 0.87876526],
       [0.36491681, 0.00618797, 0.37810717, 0.37819357],
       [0.96177198, 0.20473483, 0.92157555, 0.9207381 ],
       [0.64062207, 0.05385356, 0.71754891, 0.34082316],
       [0.53944071, 0.10703197, 0.05702623, 0.7146925 ]])

In [61]:
#how to access partiular element
#This will acheive via indexing and slicing

a16=np.random.rand(20)
a16
#this generated 20 numbers
# now i need 11 element(so It will start from 0 so that why we have taken 12 element)

a16[12]

0.27533134952298854

In [62]:
a17=np.random.rand(5,4)
a17

array([[0.51168317, 0.35964274, 0.47293515, 0.53216932],
       [0.84649075, 0.89634938, 0.81421384, 0.06301967],
       [0.00808464, 0.10085485, 0.71590022, 0.58568967],
       [0.73453669, 0.62116201, 0.08625955, 0.82768124],
       [0.4044013 , 0.58331144, 0.76063781, 0.60672939]])

In [64]:
#for example now you need only first two rows
#this will fetch first two rows but here nake sure we had used indexing

a17[:2]

array([[0.51168317, 0.35964274, 0.47293515, 0.53216932],
       [0.84649075, 0.89634938, 0.81421384, 0.06301967]])

In [66]:
#for example now you need only first two rows
#this will fetch first two rows but here nake sure we had used indexing

a17[:2][1:]

array([[0.84649075, 0.89634938, 0.81421384, 0.06301967]])