In [1]:
import numpy as np

In [3]:
#Broadcasting example in numpy

data1=np.arange(0,40,10)
data1

array([ 0, 10, 20, 30])

In [4]:
#now we want same elements mutiple times that is called broadcasting
#here what we will do we will use tile function(you can remember this concepts with washroom tiles where we have same thing one type of tile mutiples times)

data2= np.tile(np.arange(0,40,10),(3,1))
data2
#here (3,1) means same matrix we need three times

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [5]:

data3= np.tile(np.arange(0,40,10),(3,2))
data3
#here (3,2) means same matrix we need three times specially according to rows
#and we need columns 2 times

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [8]:
#for exmple if you want to tranpose this

a=data2.T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [15]:
#same basic operations on numpy array

data4=np.array([1,2,3,4,5])
data4

#add 200 value to each element
print(data4)
#here 200 value is a scalar value, sclar means this value will add in each element
data5=data4+200
print(data5)

[1 2 3 4 5]
[201 202 203 204 205]


In [12]:
type(data4)

numpy.ndarray

In [17]:
#let try to add two array
data4=np.array([1,2,3,4,5])
data4

#two array also we can add directly
data6=data4+data5
data6


array([202, 204, 206, 208, 210])

In [18]:
#anothe basic opeartor for example we want to caluclate the power of each element
#for calculating the power we are using the ***

data7=np.array([2,1,33,44,55])

data7**2

array([   4,    1, 1089, 1936, 3025], dtype=int32)

In [29]:
#what happend if one arry is 1d and another array is 2d then how addtion will perform

data8=np.array([1,2,3,4,5])
data9=np.array([[88,99,200,400],[55, 66,77,99]])

data9
type(data9)
type(data8)

data8+data9
#Here this will throw an error
#if you check that error broadcast error
# To handle or add this we need to learn the broadcast concepts


ValueError: operands could not be broadcast together with shapes (5,) (2,4) 

In [34]:
#basic subtraction
#this subtraction we can perform only on the array, if you peform on the list this will throw an error
data10=[1,2,2,3]
data11=[2,3,3,3]

data10=np.array(data10)
data10

data11=np.array(data11)
data11

data10-data11

array([-1, -1, -1,  0])

In [35]:
#list subtraction and it will throw an error
#type error unsupported operand type(s) for -: 'list' and 'list'

data12=[1,2,2,3]
data13=[2,3,3,3]

data12-data13

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [37]:
#let create an array with the help of ones and zero function then perform basic calculation

data14=np.ones(5)
data14

data14+1

array([2., 2., 2., 2., 2.])

In [39]:
#let create an array with the help of ones and zero function then perform basic calculation

data15=np.ones(5)
data15
data16=[1,2,3,4,5]
data15-data16

array([ 0., -1., -2., -3., -4.])

In [41]:
data17=np.zeros(6)
data17

data19=[0,0,0,0,0,0]

data17-data19

array([0., 0., 0., 0., 0., 0.])

In [44]:
#can we do basic calculation on one array and another list
#yes we can do that
#output will becaome array

data20=[1,2,3,3,44,55,66]
data21=np.ones(7)
data21

data21+data20

array([ 2.,  3.,  4.,  4., 45., 56., 67.])

In [45]:
#mutiply between two array

data22=np.ones(7)
data23=np.ones(7)+5

data22*data23

array([6., 6., 6., 6., 6., 6., 6.])

In [48]:
#let create a matrix with help of diag function
#now do the mutiplication

data24=np.diag([22,23,24,25])
data24

data25=np.diag([2,2,2,2])

data24*data25

array([[44,  0,  0,  0],
       [ 0, 46,  0,  0],
       [ 0,  0, 48,  0],
       [ 0,  0,  0, 50]])

In [49]:
#let do comparsion between two array
#for comparsion we are using == sign
#if values are matching then we will True otherwise false

data26=np.array([1,2,3,45])
data27=np.array([2,2,2,2])

data26==data27

array([False,  True, False, False])

In [50]:
#less than and greater than

data26> data27

array([False, False,  True,  True])

In [53]:
#instaed of == sign we can use the arrayequal function

np.array_equal(data26,data27)

False